services:
    frontend:
        image: ghcr.io/bronfood/bronfood:frontend
        container_name: bronfood-frontend
        restart: unless-stopped
        ports:
            - '3000:80'
        env_file:
            - ../.env
