import { UserOrder } from '../../utils/api/orderService/orderService';
import restaurant1 from './restaurant1.png';
import restaurant2 from './restaurant2.png';
import restaurant3 from './restaurant3.png';

export const mockOrders: UserOrder[] = [
    {
        id: 1001,
        order_code: 'ORD-1001',
        amount: 7850.0,
        currency: 'KZT',
        restaurant: { id: 1, photo: restaurant1, name: 'Jahu', rating: 4.8, address: 'ул. Березовая 21', coordinates: { latitude: 0, longitude: 0 }, workingTime: '09:00-22:00', isFavorite: false, type: 'fastFood', description: 'Изысканные блюда европейской кухни. К нам хочется вернуться.' },
        meals: [
            {
                meal: {
                    id: 101,
                    name: 'Чизбургер',
                    description: 'Классический бургер с сыром',
                    photo: 'https://example.com/meals/cheeseburger.jpg',
                    price: 2500.0,
                    type: 'food',
                    waitingTime: 15,
                    hasFeatures: true,
                },
                count: 2,
                choices: [
                    {
                        choice: {
                            id: 201,
                            name: 'Двойной сыр',
                            price: 300,
                            default: false,
                            feature_name: 'Дополнительные ингредиенты',
                            chosen: true,
                        },
                        is_visible: true,
                        is_deleted: false,
                    },
                    {
                        choice: {
                            id: 202,
                            name: 'Острый соус',
                            price: 150,
                            default: false,
                            feature_name: 'Соусы',
                            chosen: true,
                        },
                        is_visible: true,
                        is_deleted: false,
                    },
                ],
                is_visible: true,
                is_deleted: false,
            },
            {
                meal: {
                    id: 102,
                    name: 'Картофель фри',
                    description: 'Хрустящий картофель',
                    photo: 'https://example.com/meals/fries.jpg',
                    price: 1500.0,
                    type: 'food',
                    waitingTime: 10,
                    hasFeatures: false,
                },
                count: 1,
                choices: [],
                is_visible: true,
                is_deleted: false,
            },
        ],
        created_at: '2023-05-15',
        payed_at: '2023-05-15',
        waiting_time: '',
        status: 'выдан',
        canceled_at: null,
        cancellation_reason: null,
        issued_at: '2023-05-15',
        rating: 5,
        payment_url: null,
    },
    {
        id: 1002,
        order_code: null,
        amount: 5296.5,
        currency: 'KZT',
        restaurant: {
            id: 2,
            photo: restaurant2,
            name: 'Boom',
            rating: 0,
            address: 'ул. Морозова 56/1',
            coordinates: { latitude: 0, longitude: 0 },
            workingTime: '09:00-22:00',
            isFavorite: false,
            type: 'fastFood',
            description: 'Изысканные блюда европейской кухни. К нам хочется вернуться.',
        },
        meals: [
            {
                meal: {
                    id: 103,
                    name: 'Куриный донер',
                    description: 'Донер с курицей и свежими овощами',
                    photo: 'https://example.com/meals/chicken-doner.jpg',
                    price: 1650.0,
                    type: 'food',
                    waitingTime: 20,
                    hasFeatures: true,
                },
                count: 3,
                choices: [
                    {
                        choice: {
                            id: 203,
                            name: 'Одноразовая тарелка',
                            price: 50,
                            default: true,
                            feature_name: 'Упаковка',
                            chosen: true,
                        },
                        is_visible: true,
                        is_deleted: false,
                    },
                    {
                        choice: {
                            id: 204,
                            name: 'Средний',
                            price: 0,
                            default: true,
                            feature_name: 'Размер',
                            chosen: true,
                        },
                        is_visible: true,
                        is_deleted: false,
                    },
                    {
                        choice: {
                            id: 205,
                            name: 'Кетчуп',
                            price: 100,
                            default: false,
                            feature_name: 'Соусы',
                            chosen: true,
                        },
                        is_visible: true,
                        is_deleted: false,
                    },
                ],
                is_visible: true,
                is_deleted: false,
            },
        ],
        created_at: '2023-05-16',
        payed_at: null,
        waiting_time: '00:30:00',
        status: 'готовится',
        canceled_at: null,
        cancellation_reason: null,
        issued_at: null,
        rating: null,
        payment_url: 'https://checkout',
    },
    {
        id: 1003,
        order_code: 'ORD-1003',
        amount: 3200.0,
        currency: 'KZT',
        restaurant: { id: 3, photo: restaurant3, name: 'Moon', rating: 0, address: 'ул. Березовая 21', coordinates: { latitude: 0, longitude: 0 }, workingTime: '09:00-22:00', isFavorite: false, type: 'fastFood', description: null },
        meals: [
            {
                meal: {
                    id: 104,
                    name: 'Филадельфия',
                    description: 'Ролл с лососем и сливочным сыром',
                    photo: 'https://example.com/meals/philadelphia.jpg',
                    price: 2800.0,
                    type: 'food',
                    waitingTime: 25,
                    hasFeatures: true,
                },
                count: 1,
                choices: [
                    {
                        choice: {
                            id: 206,
                            name: 'С лососем',
                            price: 0,
                            default: true,
                            feature_name: 'Рыба',
                            chosen: true,
                        },
                        is_visible: true,
                        is_deleted: false,
                    },
                    {
                        choice: {
                            id: 207,
                            name: 'Без васаби',
                            price: 0,
                            default: false,
                            feature_name: 'Дополнения',
                            chosen: true,
                        },
                        is_visible: true,
                        is_deleted: false,
                    },
                ],
                is_visible: true,
                is_deleted: false,
            },
            {
                meal: {
                    id: 105,
                    name: 'Зеленый чай',
                    description: 'Традиционный японский чай',
                    photo: 'https://example.com/meals/green-tea.jpg',
                    price: 50.0,
                    type: 'drink',
                    waitingTime: 5,
                    hasFeatures: false,
                },
                count: 1,
                choices: [],
                is_visible: true,
                is_deleted: false,
            },
        ],
        created_at: '2023-05-17',
        payed_at: null,
        waiting_time: '',
        status: 'отменен',
        canceled_at: '2023-05-17',
        cancellation_reason: 'отсутствуют выбранные позиции',
        issued_at: null,
        rating: null,
        payment_url: null,
    },
];
