name: Bronfood Frontend Workflow

on:
    push:
        branches:
            - develop

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.USER_PASSWORD_TOKEN }}

            - name: Build and push frontend image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: infra/nginx/Dockerfile
                  push: true
                  tags: ghcr.io/bronfood/bronfood:frontend
    deploy:
        runs-on: ubuntu-latest
        needs: build-and-push
        permissions:
            contents: read
            packages: read

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Copy docker compose via ssh
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: 'infra/docker-compose.yml'
                  target: 'bronfood-frontend'

            - name: Executing remote ssh commands to deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd bronfood-frontend
                      docker compose down
                      docker compose pull
                      docker compose up -d
