name: Deploy PR previews

env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_YNDX_API_KEY: ${{ secrets.VITE_YNDX_API_KEY }}

on:
    push:
        branches: [main, master]
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - closed

permissions:
    contents: write
    pull-requests: write

concurrency: ci-${{ github.ref }}

jobs:
    build-deploy-and-preview:
        name: Deploy PR previews
        runs-on: ubuntu-latest
        steps:
            - name: Deploy PR previews
              uses: chvmvd/build-deploy-and-preview-action@v1.2.0
              with:
                  type: vite
