
name: Secrets

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        VITE_YNDX_API_KEY: ${{ secrets.VITE_YNDX_API_KEY }}
        
    steps:
      -name: test
       run: echo "My key ${{ secrets.VITE_API_URL }}"
  
