
name: Secrets

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        VITE_YNDX_API_KEY: ${{ secrets.VITE_YNDX_API_KEY }}
        
    steps:
      - name: Create annotation for build error
        run: echo "My key ${{ secrets.VITE_YNDX_API_KEY }}"

